version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: my-static-site
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf